### ISSUE TITLE
stuck in login google account

### ISSUE THREAD

**Issue by AshleyVatila** [aitay721822/mixerbox_converter#1]
完成輸入google帳號後，網頁關閉後跳出以下程式碼:
然後就又進入要我再次輸入python main.py的環節
google帳戶重新登出再登入亦無效果
mixerbox清單:https://www.mbplayer.com/list/80607392

[2023-10-13 16:38:42,120][mb2yt][INFO] 請手動登入 Google 帳號，並輸入 `yes` 繼續 [main.py:152]
請輸入 `yes` 繼續: yes
[2023-10-13 16:39:22,477][undetected_chromedriver.patcher][INFO] patching driver executable C:\Users\AshleyVatila\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe [patcher.py:346]
Traceback (most recent call last):
  File "C:\Users\AshleyVatila\Desktop\mixerbox_converter-master\main.py", line 179, in <module>
    main()
  File "C:\Users\AshleyVatila\Desktop\mixerbox_converter-master\main.py", line 158, in main
    driver = uc.Chrome(user_data_dir=user_data_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AshleyVatila\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 398, in __init__
    if headless or options.headless:
                   ^^^^^^^^^^^^^^^^
AttributeError: 'ChromeOptions' object has no attribute 'headless'

C:\Users\AshleyVatila\Desktop\mixerbox_converter-master>
[mb2yt.log](https://github.com/aitay721822/mixerbox_converter/files/12891394/mb2yt.log)

**Comment by aitay721822** [comment]
問題:
`undetected_chromedriver` 這個套件，需要其依賴項 `selenium` 版本低於 **4.12.0(含)**，才能不開啟 headless mode。

解決方案:
固定 `selenium` 版本為 `4.12.0`，在專案目錄底下開啟 cmd 後輸入兩條指令重新安裝即可
1. pip uninstall --yes -r requirements.txt
2. pip install --yes -r requirements.txt
